10 CLEAR 100: CLS
20 PRINT TAB(8);"LINE INPUT STATEMENT":PRINT
30 PRINT:PRINT "*** ENTER TEXT ***"
50 A$="" 'SET A$ TO NULL STRING
60 LINE INPUT "==>";A$
70 IF A$="" THEN END 'IF STILL NULL STRING, STOP!
80 PRINT A$
90 GOTO 50
