10 CLS
20 PRINT "SQUANCHY BASIC IS COLOR BASIC"
30 PRINT "REASSEMBLED TO BE AS HIGH IN"
40 PRINT "A 64K COLOR COMPUTER'S RAM AS"
50 PRINT "POSSIBLE."
60 PRINT "THIS SHOULD PRODUCE A BASIC THATIS 100% COMPAITABLE, AND ALLOWS"
70 PRINT "LARGER PROGRAMS TO RUN."
70 PRINT "PROGRAMS THAT DEPEND ON ANY"
80 PRINT "INTERNAL ASPECT OF THE"
90 PRINT "INTERPRETER, EVEN THE"
100 PRINT "DOCUMENTED ONES, WILL NOT"
110 PRINT "WORK."
120 PRINT
130 PRINT "GITHUB.COM/TLINDNER/SQUANCHY-BASIC"
140 GOTO 140
